# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_transaction.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res_new_window_rc


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(280, 370)
        Dialog.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(174, 0, 255, 255), stop:0.681818 rgba(45, 27, 102, 255));\n"
"font: 12pt \"Calibri\";")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setStyleSheet("background-color: rgba(255, 255, 255, 50);\n"
"border: 1px solid rgba(255, 255, 255, 60);\n"
"border-radius: 7px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_new_transaction = QtWidgets.QLabel(self.frame)
        self.lbl_new_transaction.setStyleSheet("color: white;\n"
"font-weight: bold;\n"
"font-size: 20pt;\n"
"background-color: none;\n"
"border: none;")
        self.lbl_new_transaction.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_new_transaction.setObjectName("lbl_new_transaction")
        self.verticalLayout.addWidget(self.lbl_new_transaction)
        self.cb_category = QtWidgets.QComboBox(self.frame)
        self.cb_category.setStyleSheet("QComboBox{\n"
"    font-size: 16pt;\n"
"    color: white;\n"
"}\n"
"QComboBox:item{\n"
"    color: black;\n"
"}")
        self.cb_category.setEditable(False)
        self.cb_category.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.cb_category.setDuplicatesEnabled(False)
        self.cb_category.setObjectName("cb_category")
        self.cb_category.addItem("")
        self.cb_category.addItem("")
        self.cb_category.addItem("")
        self.cb_category.addItem("")
        self.verticalLayout.addWidget(self.cb_category)
        self.data = QtWidgets.QDateEdit(self.frame)
        self.data.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"padding-left: 10px;")
        self.data.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.data.setDate(QtCore.QDate(2023, 1, 1))
        self.data.setObjectName("data")
        self.verticalLayout.addWidget(self.data)
        self.le_description = QtWidgets.QLineEdit(self.frame)
        self.le_description.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"padding-left: 10px;")
        self.le_description.setObjectName("le_description")
        self.verticalLayout.addWidget(self.le_description)
        self.le_balance = QtWidgets.QLineEdit(self.frame)
        self.le_balance.setStyleSheet("color: white;\n"
"font-size: 16pt;\n"
"padding-left: 10px;")
        self.le_balance.setObjectName("le_balance")
        self.verticalLayout.addWidget(self.le_balance)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    font-size: 16pt;\n"
"    color: white;\n"
"}\n"
"QComboBox:item{\n"
"    color: black;\n"
"}")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.button_new_transaction = QtWidgets.QPushButton(self.frame)
        self.button_new_transaction.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgba(255, 255, 255, 50);\n"
"border: 1px solid rgba(255, 255, 255, 60);\n"
"border-radius: 7px;\n"
"widht: 230px;\n"
"height: 50px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgba(255, 255, 255, 60);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgba(255, 255, 255, 90);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/add_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_new_transaction.setIcon(icon)
        self.button_new_transaction.setIconSize(QtCore.QSize(24, 24))
        self.button_new_transaction.setObjectName("button_new_transaction")
        self.verticalLayout.addWidget(self.button_new_transaction)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Dialog)
        self.cb_category.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New_transaction"))
        self.lbl_new_transaction.setText(_translate("Dialog", "Новая операция"))
        self.cb_category.setCurrentText(_translate("Dialog", "Сырьё"))
        self.cb_category.setItemText(0, _translate("Dialog", "Сырьё"))
        self.cb_category.setItemText(1, _translate("Dialog", "Зарплата"))
        self.cb_category.setItemText(2, _translate("Dialog", "Электр-во"))
        self.cb_category.setItemText(3, _translate("Dialog", "Прочее"))
        self.le_description.setPlaceholderText(_translate("Dialog", "Описание"))
        self.le_balance.setPlaceholderText(_translate("Dialog", "Сумма"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Прибыль"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Расход"))
        self.button_new_transaction.setText(_translate("Dialog", "Добавить операцию"))